# Generated by Django 2.2 on 2019-03-11 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewProfile',
            new_name='NewProfileModel',
        ),
    ]
