# Generated by Django 2.2 on 2019-03-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0003_auto_20190311_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='directions',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='ingredients',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='foreignkeyToNewProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipeApp.NewProfileModel'),
        ),
    ]
