# Generated by Django 2.2 on 2019-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0004_auto_20190311_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='directions',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
