# Generated by Django 2.2 on 2019-03-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0005_auto_20190311_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newprofilemodel',
            old_name='profilepic',
            new_name='profileURL',
        ),
        migrations.RenameField(
            model_name='recipemodel',
            old_name='picture',
            new_name='imageURL',
        ),
    ]
