# Generated by Django 2.2 on 2019-03-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0006_auto_20190311_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
